remote_theme: pmarsceill/just-the-docs

title: Chocolate Factory
description: Chocolate Factory 是一款开源的 AI Agent 应用引擎/应用框架，旨在帮助您轻松打造强大的 SDLC + LLM 生成助手。无论您是需要生成前端页面、后端 API、SQL 图表，还是测试用例数据，Chocolate Factory 都能满足您的需求。

heading_anchors: true

footer_content: "This code is distributed under the MPL 2.0 license. See `LICENSE` in this directory."

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/unit-mesh/chocolate-factory" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs are served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 4
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false


# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: G-JR0EZ3NLE1
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

url: "https://framework.unitmesh.cc" # the base hostname & protocol for your site

# Aux links for the upper right navigation
aux_links:
  "View in on GitHub":
    - "//github.com/unit-mesh/chocolate-factory"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.4.0"


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
